# Issue Types
- name: bug
  color: d73a4a
  description: Something isn't working

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: question
  color: d876e3
  description: Further information is requested

# Contribution Labels
- name: good first issue
  color: 7057ff
  description: Good for newcomers

- name: help wanted
  color: 008672
  description: Extra attention is needed

# Status Labels
- name: triage
  color: ededed
  description: Needs initial review and categorization

- name: needs-info
  color: ffffff
  description: Waiting for more information from reporter

- name: wontfix
  color: ffffff
  description: This will not be worked on

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: invalid
  color: e4e669
  description: This doesn't seem right

- name: stale
  color: ededed
  description: No recent activity

# Priority Labels
- name: priority:critical
  color: b60205
  description: Must be fixed ASAP

- name: priority:high
  color: d93f0b
  description: High priority issue

- name: priority:medium
  color: fbca04
  description: Medium priority issue

- name: priority:low
  color: 0e8a16
  description: Low priority issue

# Area Labels
- name: area:core
  color: 1d76db
  description: Related to @pocket/core

- name: area:react
  color: 61dafb
  description: Related to @pocket/react

- name: area:sync
  color: 5319e7
  description: Related to @pocket/sync

- name: area:server
  color: 006b75
  description: Related to @pocket/server

- name: area:storage
  color: bfd4f2
  description: Related to storage adapters

- name: area:docs
  color: 0075ca
  description: Related to documentation

- name: area:ci
  color: f9d0c4
  description: Related to CI/CD and automation

# Dependency Labels (auto-applied by Dependabot)
- name: dependencies
  color: 0366d6
  description: Pull requests that update a dependency file

- name: github-actions
  color: 000000
  description: Pull requests that update GitHub Actions
