import { describe, it, expect, beforeAll } from 'vitest';
import { resolve } from 'node:path';
import { parseOpenAPI } from '../../../src/parsers/openapi/index.js';
import { ClientGenerator } from '../../../src/generators/client/index.js';
import type { IRSchema } from '../../../src/ir/types.js';

describe('Client Generator', () => {
  let schema: IRSchema;
  let generatedCode: string;

  beforeAll(async () => {
    const fixturesPath = resolve(__dirname, '../../fixtures/openapi/petstore.yaml');
    schema = await parseOpenAPI(fixturesPath);

    const generator = new ClientGenerator(schema, {
      outputDir: '/tmp/test-output',
    });
    generator.generate();
    generatedCode = generator['printer'].toString();
  });

  describe('imports generation', () => {
    it('should import types from types file', () => {
      expect(generatedCode).toContain("from './types.js'");
    });

    it('should import params types', () => {
      expect(generatedCode).toContain('ListPetsParams');
      expect(generatedCode).toContain('GetPetParams');
    });

    it('should import response types', () => {
      expect(generatedCode).toContain('ListPetsResponse');
      expect(generatedCode).toContain('GetPetResponse');
    });
  });

  describe('client class generation', () => {
    it('should generate ApiClient class', () => {
      expect(generatedCode).toContain('export class ApiClient');
    });

    it('should generate constructor with config', () => {
      expect(generatedCode).toContain('constructor(config?: Partial<ClientConfig>)');
    });

    it('should generate listPets method', () => {
      expect(generatedCode).toContain('async listPets(');
    });

    it('should generate getPet method', () => {
      expect(generatedCode).toContain('async getPet(');
    });

    it('should support AbortSignal', () => {
      expect(generatedCode).toContain('signal?: AbortSignal');
    });

    it('should export default client instance', () => {
      expect(generatedCode).toContain('export const apiClient = new ApiClient()');
    });
  });

  describe('HTTP client base generation', () => {
    it('should generate HttpClient class', () => {
      expect(generatedCode).toContain('class HttpClient');
    });

    it('should generate ClientConfig interface', () => {
      expect(generatedCode).toContain('interface ClientConfig');
    });

    it('should generate RequestOptions interface', () => {
      expect(generatedCode).toContain('interface RequestOptions');
    });

    it('should generate request method', () => {
      expect(generatedCode).toContain('async request<T>');
    });
  });

  describe('code formatting', () => {
    it('should include auto-generated comment', () => {
      expect(generatedCode).toContain('This file was auto-generated by Bridge');
    });
  });
});

describe('Client Generator - Function Style', () => {
  let schema: IRSchema;
  let generatedCode: string;

  beforeAll(async () => {
    const fixturesPath = resolve(__dirname, '../../fixtures/openapi/petstore.yaml');
    schema = await parseOpenAPI(fixturesPath);

    const generator = new ClientGenerator(schema, {
      outputDir: '/tmp/test-output',
      style: 'functions',
    });
    generator.generate();
    generatedCode = generator['printer'].toString();
  });

  it('should generate standalone functions', () => {
    expect(generatedCode).toContain('export async function listPets');
    expect(generatedCode).toContain('export async function getPet');
  });

  it('should generate configureClient function', () => {
    expect(generatedCode).toContain('export function configureClient');
  });

  it('should not generate ApiClient class', () => {
    expect(generatedCode).not.toContain('export class ApiClient');
  });
});

describe('Client Generator - Custom Base URL', () => {
  let schema: IRSchema;

  beforeAll(async () => {
    const fixturesPath = resolve(__dirname, '../../fixtures/openapi/petstore.yaml');
    schema = await parseOpenAPI(fixturesPath);
  });

  it('should use custom base URL', () => {
    const generator = new ClientGenerator(schema, {
      outputDir: '/tmp/test-output',
      baseUrl: 'https://custom-api.example.com',
    });
    generator.generate();
    const code = generator['printer'].toString();

    expect(code).toContain('https://custom-api.example.com');
  });
});

describe('Client Generator - Edge Cases', () => {
  it('should handle empty schema', () => {
    const emptySchema: IRSchema = {
      metadata: {
        title: 'Empty API',
        version: '1.0.0',
        source: 'openapi',
      },
      types: new Map(),
      endpoints: [],
      operations: [],
    };

    const generator = new ClientGenerator(emptySchema, {
      outputDir: '/tmp/test-output',
    });
    generator.generate();
    const code = generator['printer'].toString();

    expect(code).toContain('This file was auto-generated by Bridge');
    expect(code).toContain('class HttpClient');
  });
});
