import { describe, it, expect, beforeAll } from 'vitest';
import { resolve } from 'node:path';
import { parseOpenAPI } from '../../../src/parsers/openapi/index.js';
import { MswGenerator } from '../../../src/generators/msw/index.js';
import type { IRSchema } from '../../../src/ir/types.js';

describe('MSW Generator', () => {
  let schema: IRSchema;
  let generatedCode: string;

  beforeAll(async () => {
    const fixturesPath = resolve(__dirname, '../../fixtures/openapi/petstore.yaml');
    schema = await parseOpenAPI(fixturesPath);

    const generator = new MswGenerator(schema, {
      outputDir: '/tmp/test-output',
    });
    generator.generate();
    generatedCode = generator['printer'].toString();
  });

  describe('imports generation', () => {
    it('should import http from msw', () => {
      expect(generatedCode).toContain("import { http, HttpResponse } from 'msw'");
    });

    it('should import types', () => {
      expect(generatedCode).toContain("from './types.js'");
    });
  });

  describe('mock data factories generation', () => {
    it('should generate mock factory helper functions', () => {
      expect(generatedCode).toContain('export function generateId()');
      expect(generatedCode).toContain('export function randomElement');
      expect(generatedCode).toContain('export function randomInt');
    });
  });

  describe('request handlers generation', () => {
    it('should generate http handlers', () => {
      expect(generatedCode).toContain('http.');
    });

    it('should generate HttpResponse usage', () => {
      expect(generatedCode).toContain('HttpResponse');
    });
  });

  describe('code formatting', () => {
    it('should include auto-generated comment', () => {
      expect(generatedCode).toContain('This file was auto-generated by Bridge');
    });
  });
});

describe('MSW Generator - Options', () => {
  let schema: IRSchema;

  beforeAll(async () => {
    const fixturesPath = resolve(__dirname, '../../fixtures/openapi/petstore.yaml');
    schema = await parseOpenAPI(fixturesPath);
  });

  it('should use custom base URL', () => {
    const generator = new MswGenerator(schema, {
      outputDir: '/tmp/test-output',
      baseUrl: 'https://api.example.com',
    });
    generator.generate();
    const code = generator['printer'].toString();

    expect(code).toContain('https://api.example.com');
  });

  it('should skip fakers when disabled', () => {
    const generator = new MswGenerator(schema, {
      outputDir: '/tmp/test-output',
      includeFakers: false,
    });
    generator.generate();
    const code = generator['printer'].toString();

    expect(code).not.toMatch(/export\s+function\s+fake\w+/);
  });
});

describe('MSW Generator - Edge Cases', () => {
  it('should handle empty schema', () => {
    const emptySchema: IRSchema = {
      metadata: {
        title: 'Empty API',
        version: '1.0.0',
        source: 'openapi',
      },
      types: new Map(),
      endpoints: [],
      operations: [],
    };

    const generator = new MswGenerator(emptySchema, {
      outputDir: '/tmp/test-output',
    });
    generator.generate();
    const code = generator['printer'].toString();

    expect(code).toContain('This file was auto-generated by Bridge');
    expect(code).toContain("import { http, HttpResponse } from 'msw'");
  });

  it('should handle schema with no object types', () => {
    const noObjectSchema: IRSchema = {
      metadata: {
        title: 'No Objects API',
        version: '1.0.0',
        source: 'openapi',
      },
      types: new Map([
        ['Status', { kind: 'enum', name: 'Status', values: ['active', 'inactive'] }],
      ]),
      endpoints: [
        {
          operationId: 'getStatus',
          path: '/status',
          method: 'get',
          parameters: [],
          responses: [{ statusCode: '200', description: 'OK', content: [] }],
        },
      ],
      operations: [],
    };

    const generator = new MswGenerator(noObjectSchema, {
      outputDir: '/tmp/test-output',
    });
    generator.generate();
    const code = generator['printer'].toString();

    expect(code).toContain("import { http, HttpResponse } from 'msw'");
  });
});
