import { describe, it, expect, beforeAll } from 'vitest';
import { resolve } from 'node:path';
import { parseOpenAPI } from '../../../src/parsers/openapi/index.js';
import { ZodGenerator } from '../../../src/generators/zod/index.js';
import type { IRSchema } from '../../../src/ir/types.js';

describe('Zod Generator', () => {
  let schema: IRSchema;
  let generatedCode: string;

  beforeAll(async () => {
    const fixturesPath = resolve(__dirname, '../../fixtures/openapi/petstore.yaml');
    schema = await parseOpenAPI(fixturesPath);

    const generator = new ZodGenerator(schema, {
      outputDir: '/tmp/test-output',
    });
    generator.generate();
    generatedCode = generator['printer'].toString();
  });

  describe('schema generation', () => {
    it('should import zod', () => {
      expect(generatedCode).toContain("import { z } from 'zod'");
    });

    it('should generate Pet schema', () => {
      expect(generatedCode).toContain('export const petSchema');
    });

    it('should generate Owner schema', () => {
      expect(generatedCode).toContain('export const ownerSchema');
    });

    it('should generate Error schema', () => {
      expect(generatedCode).toContain('export const errorSchema');
    });

    it('should generate PetStatus enum schema', () => {
      expect(generatedCode).toContain('export const petStatusSchema');
      expect(generatedCode).toContain('z.enum');
    });
  });

  describe('endpoint schemas generation', () => {
    it('should generate params schemas for endpoints', () => {
      expect(generatedCode).toContain('export const listPetsParamsSchema');
      expect(generatedCode).toContain('export const getPetParamsSchema');
    });

    it('should generate response schemas for endpoints', () => {
      expect(generatedCode).toContain('export const listPetsResponseSchema');
      expect(generatedCode).toContain('export const getPetResponseSchema');
    });
  });

  describe('inferred types generation', () => {
    it('should generate inferred types section', () => {
      expect(generatedCode).toContain('=== Inferred Types ===');
    });

    it('should generate z.infer types', () => {
      expect(generatedCode).toContain('z.infer<typeof petSchema>');
      expect(generatedCode).toContain('z.infer<typeof ownerSchema>');
    });

    it('should generate endpoint infer types', () => {
      expect(generatedCode).toContain('z.infer<typeof listPetsParamsSchema>');
      expect(generatedCode).toContain('z.infer<typeof listPetsResponseSchema>');
    });
  });

  describe('code formatting', () => {
    it('should include auto-generated comment', () => {
      expect(generatedCode).toContain('This file was auto-generated by Bridge');
    });

    it('should generate valid Zod syntax', () => {
      expect(generatedCode).toContain('z.object');
      expect(generatedCode).toContain('z.string()');
    });
  });
});

describe('Zod Generator - Options', () => {
  let schema: IRSchema;

  beforeAll(async () => {
    const fixturesPath = resolve(__dirname, '../../fixtures/openapi/petstore.yaml');
    schema = await parseOpenAPI(fixturesPath);
  });

  it('should skip infer types when disabled', () => {
    const generator = new ZodGenerator(schema, {
      outputDir: '/tmp/test-output',
      inferTypes: false,
    });
    generator.generate();
    const code = generator['printer'].toString();

    expect(code).not.toContain('=== Inferred Types ===');
  });

  it('should skip endpoint schemas when disabled', () => {
    const generator = new ZodGenerator(schema, {
      outputDir: '/tmp/test-output',
      generateEndpointSchemas: false,
    });
    generator.generate();
    const code = generator['printer'].toString();

    expect(code).not.toContain('=== Endpoint Schemas ===');
    expect(code).not.toContain('listPetsParamsSchema');
  });
});

describe('Zod Generator - Edge Cases', () => {
  it('should handle empty schema', () => {
    const emptySchema: IRSchema = {
      metadata: {
        title: 'Empty API',
        version: '1.0.0',
        source: 'openapi',
      },
      types: new Map(),
      endpoints: [],
      operations: [],
    };

    const generator = new ZodGenerator(emptySchema, {
      outputDir: '/tmp/test-output',
    });
    generator.generate();
    const code = generator['printer'].toString();

    expect(code).toContain('This file was auto-generated by Bridge');
    expect(code).toContain("import { z } from 'zod'");
  });
});
