name: Bug Report
description: Report a bug or unexpected behavior
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run command '...'
        2. With input file '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead.
    validations:
      required: true

  - type: textarea
    id: input
    attributes:
      label: Input Specification
      description: If applicable, provide your OpenAPI/GraphQL spec (or a minimal reproduction).
      render: yaml

  - type: dropdown
    id: input-type
    attributes:
      label: Input Type
      options:
        - OpenAPI 3.0
        - OpenAPI 3.1
        - GraphQL
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Bridge Version
      description: What version of Bridge are you using?
      placeholder: '0.1.0'
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: '20.10.0'
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
