name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Create a database with...
        2. Insert a document...
        3. Query with...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, it...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Reproduction Code
      description: Provide minimal code to reproduce the issue.
      render: typescript
      placeholder: |
        import { Database, createIndexedDBStorage } from 'pocket';

        const db = await Database.create({
          name: 'test',
          storage: createIndexedDBStorage(),
        });

        // Code that demonstrates the bug

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package(s) are you using?
      multiple: true
      options:
        - pocket
        - "@pocket/core"
        - "@pocket/react"
        - "@pocket/sync"
        - "@pocket/storage-indexeddb"
        - "@pocket/storage-opfs"
        - "@pocket/storage-memory"
        - "@pocket/server"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of the package are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) are affected?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Node.js
        - Other

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "macOS 14.0, Windows 11, Ubuntu 22.04"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
