// This file was auto-generated by Bridge
// Do not edit this file directly

import { useSWR, SWRConfiguration } from 'swr';
import { useSWRMutation, SWRMutationConfiguration } from 'swr/mutation';

import { apiClient } from './client.js';

import type {
  ListPetsParams,
  ListPetsResponse,
  CreatePetParams,
  CreatePetResponse,
  GetPetParams,
  GetPetResponse,
  UpdatePetParams,
  UpdatePetResponse,
  DeletePetParams,
  DeletePetResponse,
  UploadPetPhotoParams,
  UploadPetPhotoResponse,
} from './types.js';

/**
 * SWR cache keys for revalidation
 */
export const swrKeys = {
  listPets: (params: ListPetsParams) => ['listPets', params] as const,
  getPet: (params: GetPetParams) => ['getPet', params] as const,
} as const;

// === SWR Query Hooks ===

/**
 * List all pets
 */
export function useListPets(
  params: ListPetsParams | null,
  options?: SWRConfiguration<ListPetsResponse, Error>
) {
  return useSWR<ListPetsResponse, Error>(
    params ? swrKeys.listPets(params) : null,
    params ? () => apiClient.listPets(params) : null,
    options
  );
}

/**
 * Get a pet by ID
 */
export function useGetPet(
  params: GetPetParams | null,
  options?: SWRConfiguration<GetPetResponse, Error>
) {
  return useSWR<GetPetResponse, Error>(
    params ? swrKeys.getPet(params) : null,
    params ? () => apiClient.getPet(params) : null,
    options
  );
}

// === SWR Mutation Hooks ===

/**
 * Create a pet
 */
export function useCreatePet(
  options?: SWRMutationConfiguration<CreatePetResponse, Error, string, CreatePetParams>
) {
  return useSWRMutation<CreatePetResponse, Error, string, CreatePetParams>(
    'createPet',
    (_, { arg }) => apiClient.createPet(arg),
    options
  );
}

/**
 * Update a pet
 */
export function useUpdatePet(
  options?: SWRMutationConfiguration<UpdatePetResponse, Error, string, UpdatePetParams>
) {
  return useSWRMutation<UpdatePetResponse, Error, string, UpdatePetParams>(
    'updatePet',
    (_, { arg }) => apiClient.updatePet(arg),
    options
  );
}

/**
 * Delete a pet
 */
export function useDeletePet(
  options?: SWRMutationConfiguration<DeletePetResponse, Error, string, DeletePetParams>
) {
  return useSWRMutation<DeletePetResponse, Error, string, DeletePetParams>(
    'deletePet',
    (_, { arg }) => apiClient.deletePet(arg),
    options
  );
}

/**
 * Upload a pet photo
 */
export function useUploadPetPhoto(
  options?: SWRMutationConfiguration<UploadPetPhotoResponse, Error, string, UploadPetPhotoParams>
) {
  return useSWRMutation<UploadPetPhotoResponse, Error, string, UploadPetPhotoParams>(
    'uploadPetPhoto',
    (_, { arg }) => apiClient.uploadPetPhoto(arg),
    options
  );
}
