// This file was auto-generated by Bridge
// Do not edit this file directly

import { useQuery, useMutation, UseQueryOptions, UseMutationOptions } from '@tanstack/react-query';

import { apiClient } from './client.js';

import type {
  ListPetsParams,
  ListPetsResponse,
  CreatePetParams,
  CreatePetResponse,
  GetPetParams,
  GetPetResponse,
  UpdatePetParams,
  UpdatePetResponse,
  DeletePetParams,
  DeletePetResponse,
  UploadPetPhotoParams,
  UploadPetPhotoResponse,
} from './types.js';

/**
 * Query keys for cache management and invalidation
 */
export const queryKeys = {
  listPets: (params: ListPetsParams) => ['listPets', params] as const,
  getPet: (params: GetPetParams) => ['getPet', params] as const,
} as const;

export type QueryKeys = typeof queryKeys;

// === Query Hooks ===

/**
 * List all pets
 */
export function useListPets(
  params: ListPetsParams,
  options?: Omit<UseQueryOptions<ListPetsResponse, Error>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: queryKeys.listPets(params),
    queryFn: ({ signal }) => apiClient.listPets(params, signal),
    ...options,
  });
}

/**
 * Get a pet by ID
 */
export function useGetPet(
  params: GetPetParams,
  options?: Omit<UseQueryOptions<GetPetResponse, Error>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: queryKeys.getPet(params),
    queryFn: ({ signal }) => apiClient.getPet(params, signal),
    ...options,
  });
}

// === Mutation Hooks ===

/**
 * Create a pet
 */
export function useCreatePet(
  options?: UseMutationOptions<CreatePetResponse, Error, CreatePetParams>
) {
  return useMutation({
    mutationFn: (params) => apiClient.createPet(params),
    ...options,
  });
}

/**
 * Update a pet
 */
export function useUpdatePet(
  options?: UseMutationOptions<UpdatePetResponse, Error, UpdatePetParams>
) {
  return useMutation({
    mutationFn: (params) => apiClient.updatePet(params),
    ...options,
  });
}

/**
 * Delete a pet
 */
export function useDeletePet(
  options?: UseMutationOptions<DeletePetResponse, Error, DeletePetParams>
) {
  return useMutation({
    mutationFn: (params) => apiClient.deletePet(params),
    ...options,
  });
}

/**
 * Upload a pet photo
 */
export function useUploadPetPhoto(
  options?: UseMutationOptions<UploadPetPhotoResponse, Error, UploadPetPhotoParams>
) {
  return useMutation({
    mutationFn: (params) => apiClient.uploadPetPhoto(params),
    ...options,
  });
}
