// This file was auto-generated by Bridge
// Do not edit this file directly

import { http, HttpResponse } from 'msw';

import type { Pet, Owner, CreatePetRequest, UpdatePetRequest, Photo, Error } from './types.js';

// === Mock Data Factories ===

export function generateId(): string {
  return Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
}

export function randomElement<T>(arr: readonly T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]!;
}

export function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

export function randomBoolean(): boolean {
  return Math.random() > 0.5;
}

export function randomDate(start?: Date, end?: Date): string {
  const s = start ?? new Date(2020, 0, 1);
  const e = end ?? new Date();
  return new Date(s.getTime() + Math.random() * (e.getTime() - s.getTime())).toISOString();
}

export const SAMPLE_WORDS = [
  'lorem',
  'ipsum',
  'dolor',
  'sit',
  'amet',
  'consectetur',
  'adipiscing',
  'elit',
  'sed',
  'do',
  'eiusmod',
  'tempor',
];

export function randomWord(): string {
  return randomElement(SAMPLE_WORDS);
}

export function randomSentence(wordCount?: number): string {
  const count = wordCount ?? randomInt(3, 8);
  return Array.from({ length: count }, () => randomWord()).join(' ');
}

export function randomEmail(): string {
  return `${randomWord()}${randomInt(1, 999)}@example.com`;
}

export function randomUrl(): string {
  return `https://example.com/${randomWord()}/${generateId()}`;
}

/**
 * Create mock Pet data
 *
 * @param overrides - Optional property overrides
 */
export function mockPet(overrides: Partial<Pet> = {}): Pet {
  return {
    id: generateId(),
    name: randomWord(),
    species:
      overrides.species !== undefined
        ? overrides.species
        : randomElement(['dog', 'cat', 'bird', 'fish', 'other'] as const),
    breed: overrides.breed !== undefined ? overrides.breed : randomWord(),
    age: overrides.age !== undefined ? overrides.age : randomInt(0, 100),
    status: randomElement(['available', 'pending', 'sold'] as const),
    tags: overrides.tags !== undefined ? overrides.tags : [randomWord(), randomWord()],
    owner: overrides.owner !== undefined ? overrides.owner : mockOwner(),
    createdAt: randomWord(),
    updatedAt: overrides.updatedAt !== undefined ? overrides.updatedAt : randomWord(),
    ...overrides,
  };
}

/**
 * Create mock Owner data
 *
 * @param overrides - Optional property overrides
 */
export function mockOwner(overrides: Partial<Owner> = {}): Owner {
  return {
    id: generateId(),
    name: randomWord(),
    email: randomEmail(),
    phone: overrides.phone !== undefined ? overrides.phone : randomWord(),
    ...overrides,
  };
}

/**
 * Create mock CreatePetRequest data
 *
 * @param overrides - Optional property overrides
 */
export function mockCreatePetRequest(overrides: Partial<CreatePetRequest> = {}): CreatePetRequest {
  return {
    name: randomWord(),
    species:
      overrides.species !== undefined
        ? overrides.species
        : randomElement(['dog', 'cat', 'bird', 'fish', 'other'] as const),
    breed: overrides.breed !== undefined ? overrides.breed : randomWord(),
    age: overrides.age !== undefined ? overrides.age : randomInt(0, 100),
    tags: overrides.tags !== undefined ? overrides.tags : [randomWord(), randomWord()],
    ...overrides,
  };
}

/**
 * Create mock UpdatePetRequest data
 *
 * @param overrides - Optional property overrides
 */
export function mockUpdatePetRequest(overrides: Partial<UpdatePetRequest> = {}): UpdatePetRequest {
  return {
    name: overrides.name !== undefined ? overrides.name : randomWord(),
    species:
      overrides.species !== undefined
        ? overrides.species
        : randomElement(['dog', 'cat', 'bird', 'fish', 'other'] as const),
    breed: overrides.breed !== undefined ? overrides.breed : randomWord(),
    age: overrides.age !== undefined ? overrides.age : randomInt(0, 100),
    status:
      overrides.status !== undefined
        ? overrides.status
        : randomElement(['available', 'pending', 'sold'] as const),
    tags: overrides.tags !== undefined ? overrides.tags : [randomWord(), randomWord()],
    ...overrides,
  };
}

/**
 * Create mock Photo data
 *
 * @param overrides - Optional property overrides
 */
export function mockPhoto(overrides: Partial<Photo> = {}): Photo {
  return {
    id: generateId(),
    url: randomUrl(),
    caption: overrides.caption !== undefined ? overrides.caption : randomWord(),
    uploadedAt: overrides.uploadedAt !== undefined ? overrides.uploadedAt : randomWord(),
    ...overrides,
  };
}

/**
 * Create mock Error data
 *
 * @param overrides - Optional property overrides
 */
export function mockError(overrides: Partial<Error> = {}): Error {
  return {
    code: randomWord(),
    message: randomWord(),
    details: overrides.details !== undefined ? overrides.details : {},
    ...overrides,
  };
}

// === MSW Request Handlers ===

/**
 * Handler for GET /pets
 *
 * @description List all pets
 */
export const listPetsHandler = http.get(
  'https://api.petstore.example.com/v1/pets',
  ({ request, params }) => {
    // Access path params: params.petId, etc.
    // Access request body: await request.json()
    return HttpResponse.json([mockPet(), mockPet()]);
  }
);

/**
 * Handler for POST /pets
 *
 * @description Create a pet
 */
export const createPetHandler = http.post(
  'https://api.petstore.example.com/v1/pets',
  ({ request, params }) => {
    // Access path params: params.petId, etc.
    // Access request body: await request.json()
    return HttpResponse.json(mockPet());
  }
);

/**
 * Handler for GET /pets/{petId}
 *
 * @description Get a pet by ID
 */
export const getPetHandler = http.get(
  'https://api.petstore.example.com/v1/pets/:petId',
  ({ request, params }) => {
    // Access path params: params.petId, etc.
    // Access request body: await request.json()
    return HttpResponse.json(mockPet());
  }
);

/**
 * Handler for PUT /pets/{petId}
 *
 * @description Update a pet
 */
export const updatePetHandler = http.put(
  'https://api.petstore.example.com/v1/pets/:petId',
  ({ request, params }) => {
    // Access path params: params.petId, etc.
    // Access request body: await request.json()
    return HttpResponse.json(mockPet());
  }
);

/**
 * Handler for DELETE /pets/{petId}
 *
 * @description Delete a pet
 */
export const deletePetHandler = http.delete(
  'https://api.petstore.example.com/v1/pets/:petId',
  ({ request, params }) => {
    // Access path params: params.petId, etc.
    // Access request body: await request.json()
    return new HttpResponse(null, { status: 204 });
  }
);

/**
 * Handler for POST /pets/{petId}/photos
 *
 * @description Upload a pet photo
 */
export const uploadPetPhotoHandler = http.post(
  'https://api.petstore.example.com/v1/pets/:petId/photos',
  ({ request, params }) => {
    // Access path params: params.petId, etc.
    // Access request body: await request.json()
    return HttpResponse.json(mockPhoto());
  }
);

/**
 * All MSW handlers for this API
 */
export const handlers: ReturnType<typeof http.get>[] = [
  listPetsHandler,
  createPetHandler,
  getPetHandler,
  updatePetHandler,
  deletePetHandler,
  uploadPetPhotoHandler,
];
