// This file was auto-generated by Bridge
// Do not edit this file directly

import { z } from 'zod';

/**
 * A pet in the store
 */
export const petSchema = z.object({
  id: z.string().describe('Unique identifier for the pet'),
  name: z.string().describe('Name of the pet'),
  species: z
    .enum(['dog', 'cat', 'bird', 'fish', 'other'])
    .optional()
    .describe('Species of the pet'),
  breed: z.string().optional().describe('Breed of the pet'),
  age: z.number().int().optional().describe('Age in years'),
  status: petStatusSchema.describe('Status of the pet in the store'),
  tags: z.array(z.string()).optional().describe('Tags for categorizing the pet'),
  owner: ownerSchema.optional().describe('Pet owner information'),
  createdAt: z.string().describe('When the pet was added to the store'),
  updatedAt: z.string().optional().describe('When the pet was last updated'),
});

/**
 * Status of the pet in the store
 */
export const petStatusSchema = z.enum(['available', 'pending', 'sold']);

/**
 * Pet owner information
 */
export const ownerSchema = z.object({
  id: z.string(),
  name: z.string(),
  email: z.string(),
  phone: z.string().optional(),
});

/**
 * Request body for creating a pet
 */
export const createPetRequestSchema = z.object({
  name: z.string(),
  species: z.enum(['dog', 'cat', 'bird', 'fish', 'other']).optional(),
  breed: z.string().optional(),
  age: z.number().int().optional(),
  tags: z.array(z.string()).optional(),
});

/**
 * Request body for updating a pet
 */
export const updatePetRequestSchema = z.object({
  name: z.string().optional(),
  species: z.enum(['dog', 'cat', 'bird', 'fish', 'other']).optional(),
  breed: z.string().optional(),
  age: z.number().int().optional(),
  status: petStatusSchema.optional().describe('Status of the pet in the store'),
  tags: z.array(z.string()).optional(),
});

export const photoSchema = z.object({
  id: z.string(),
  url: z.string(),
  caption: z.string().optional(),
  uploadedAt: z.string().optional(),
});

/**
 * Error response
 */
export const errorSchema = z.object({
  code: z.string().describe('Error code'),
  message: z.string().describe('Human-readable error message'),
  details: z.record(z.string(), z.unknown()).optional().describe('Additional error details'),
});

// === Endpoint Schemas ===

export const listPetsParamsSchema = z.object({
  query: z
    .object({
      limit: z.number().int().optional(),
      offset: z.number().int().optional(),
      status: petStatusSchema.optional(),
    })
    .optional(),
});

export const listPetsResponseSchema = z.array(petSchema);

export const createPetParamsSchema = z.object({
  body: createPetRequestSchema,
});

export const createPetResponseSchema = petSchema;

export const getPetParamsSchema = z.object({
  path: z.object({
    petId: z.string(),
  }),
});

export const getPetResponseSchema = petSchema;

export const updatePetParamsSchema = z.object({
  path: z.object({
    petId: z.string(),
  }),
  body: updatePetRequestSchema,
});

export const updatePetResponseSchema = petSchema;

export const deletePetParamsSchema = z.object({
  path: z.object({
    petId: z.string(),
  }),
});

export const deletePetResponseSchema = z.void();

export const uploadPetPhotoParamsSchema = z.object({
  path: z.object({
    petId: z.string(),
  }),
  body: z.object({
    file: z.string(),
    caption: z.string().optional(),
  }),
});

export const uploadPetPhotoResponseSchema = photoSchema;

// === Inferred Types ===

export type Pet = z.infer<typeof petSchema>;
export type PetStatus = z.infer<typeof petStatusSchema>;
export type Owner = z.infer<typeof ownerSchema>;
export type CreatePetRequest = z.infer<typeof createPetRequestSchema>;
export type UpdatePetRequest = z.infer<typeof updatePetRequestSchema>;
export type Photo = z.infer<typeof photoSchema>;
export type Error = z.infer<typeof errorSchema>;

export type ListPetsParams = z.infer<typeof listPetsParamsSchema>;
export type ListPetsResponse = z.infer<typeof listPetsResponseSchema>;
export type CreatePetParams = z.infer<typeof createPetParamsSchema>;
export type CreatePetResponse = z.infer<typeof createPetResponseSchema>;
export type GetPetParams = z.infer<typeof getPetParamsSchema>;
export type GetPetResponse = z.infer<typeof getPetResponseSchema>;
export type UpdatePetParams = z.infer<typeof updatePetParamsSchema>;
export type UpdatePetResponse = z.infer<typeof updatePetResponseSchema>;
export type DeletePetParams = z.infer<typeof deletePetParamsSchema>;
export type DeletePetResponse = z.infer<typeof deletePetResponseSchema>;
export type UploadPetPhotoParams = z.infer<typeof uploadPetPhotoParamsSchema>;
export type UploadPetPhotoResponse = z.infer<typeof uploadPetPhotoResponseSchema>;
