// This file was auto-generated by Bridge
// Do not edit this file directly

/**
 * A pet in the store
 */
export interface Pet {
  /**
   * Unique identifier for the pet
   */
  id: string;
  /**
   * Name of the pet
   */
  name: string;
  /**
   * Species of the pet
   */
  species?: 'dog' | 'cat' | 'bird' | 'fish' | 'other';
  /**
   * Breed of the pet
   */
  breed?: string;
  /**
   * Age in years
   */
  age?: number;
  /**
   * Status of the pet in the store
   */
  status: PetStatus;
  /**
   * Tags for categorizing the pet
   */
  tags?: string[];
  /**
   * Pet owner information
   */
  owner?: Owner;
  /**
   * When the pet was added to the store
   */
  createdAt: string;
  /**
   * When the pet was last updated
   */
  updatedAt?: string;
}

/**
 * Status of the pet in the store
 */
export enum PetStatus {
  Available = 'available',
  Pending = 'pending',
  Sold = 'sold',
}

/**
 * Pet owner information
 */
export interface Owner {
  id: string;
  name: string;
  email: string;
  phone?: string;
}

/**
 * Request body for creating a pet
 */
export interface CreatePetRequest {
  name: string;
  species?: 'dog' | 'cat' | 'bird' | 'fish' | 'other';
  breed?: string;
  age?: number;
  tags?: string[];
}

/**
 * Request body for updating a pet
 */
export interface UpdatePetRequest {
  name?: string;
  species?: 'dog' | 'cat' | 'bird' | 'fish' | 'other';
  breed?: string;
  age?: number;
  /**
   * Status of the pet in the store
   */
  status?: PetStatus;
  tags?: string[];
}

export interface Photo {
  id: string;
  url: string;
  caption?: string;
  uploadedAt?: string;
}

/**
 * Error response
 */
export interface Error {
  /**
   * Error code
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * Additional error details
   */
  details?: Record<string, unknown>;
}

// === Endpoint Types ===

export interface ListPetsParams {
  query?: {
    limit?: number;
    offset?: number;
    status?: PetStatus;
  };
}

export type ListPetsResponse = Pet[];

export interface CreatePetParams {
  body: CreatePetRequest;
}

export type CreatePetResponse = Pet;

export interface GetPetParams {
  path: {
    petId: string;
  };
}

export type GetPetResponse = Pet;

export interface UpdatePetParams {
  path: {
    petId: string;
  };
  body: UpdatePetRequest;
}

export type UpdatePetResponse = Pet;

export interface DeletePetParams {
  path: {
    petId: string;
  };
}

export type DeletePetResponse = void;

export interface UploadPetPhotoParams {
  path: {
    petId: string;
  };
  body: { file: string; caption?: string };
}

export type UploadPetPhotoResponse = Photo;

export type OperationId =
  | 'listPets'
  | 'createPet'
  | 'getPet'
  | 'updatePet'
  | 'deletePet'
  | 'uploadPetPhoto';
