// This file was auto-generated by Bridge
// Do not edit this file directly

/**
 * A pet in the store
 */
export interface Pet {
  /**
   * Unique identifier for the pet
   */
  id: string;
  /**
   * Name of the pet
   */
  name: string;
  /**
   * Species of the pet
   */
  species?: 'dog' | 'cat' | 'bird' | 'fish' | 'other';
  /**
   * Breed of the pet
   */
  breed?: string;
  /**
   * Age in years
   */
  age?: number;
  /**
   * Status of the pet in the store
   */
  status: PetStatus;
  /**
   * Tags for categorizing the pet
   */
  tags?: string[];
  /**
   * Pet owner information
   */
  owner?: Owner;
  /**
   * When the pet was added to the store
   */
  createdAt: string;
  /**
   * When the pet was last updated
   */
  updatedAt?: string;
}

/**
 * Status of the pet in the store
 */
export enum PetStatus {
  Available = 'available',
  Pending = 'pending',
  Sold = 'sold',
}

/**
 * Pet owner information
 */
export interface Owner {
  id: string;
  name: string;
  email: string;
  phone?: string;
}

/**
 * Request body for creating a pet
 */
export interface CreatePetRequest {
  name: string;
  species?: 'dog' | 'cat' | 'bird' | 'fish' | 'other';
  breed?: string;
  age?: number;
  tags?: string[];
}

/**
 * Request body for updating a pet
 */
export interface UpdatePetRequest {
  name?: string;
  species?: 'dog' | 'cat' | 'bird' | 'fish' | 'other';
  breed?: string;
  age?: number;
  /**
   * Status of the pet in the store
   */
  status?: PetStatus;
  tags?: string[];
}

export interface Photo {
  id: string;
  url: string;
  caption?: string;
  uploadedAt?: string;
}

/**
 * Error response
 */
export interface Error {
  /**
   * Error code
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * Additional error details
   */
  details?: Record<string, unknown>;
}

// === Endpoint Types ===

export interface ListPetsParams {
  query?: {
    limit?: number;
    offset?: number;
    status?: PetStatus;
  };
}

export type ListPetsResponse = Pet[];

export interface CreatePetParams {
  body: CreatePetRequest;
}

export type CreatePetResponse = Pet;

export interface GetPetParams {
  path: {
    petId: string;
  };
}

export type GetPetResponse = Pet;

export interface UpdatePetParams {
  path: {
    petId: string;
  };
  body: UpdatePetRequest;
}

export type UpdatePetResponse = Pet;

export interface DeletePetParams {
  path: {
    petId: string;
  };
}

export type DeletePetResponse = void;

export interface UploadPetPhotoParams {
  path: {
    petId: string;
  };
  body: { file: string; caption?: string };
}

export type UploadPetPhotoResponse = Photo;

export type OperationId =
  | 'listPets'
  | 'createPet'
  | 'getPet'
  | 'updatePet'
  | 'deletePet'
  | 'uploadPetPhoto';

// === Type Guards ===

/**
 * Type guard for Pet
 *
 * @param value - The value to check
 */
export function isPet(value: unknown): value is Pet {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const obj = value as Record<string, unknown>;

  // Check required properties
  if (!('id' in obj) || !(typeof obj['id'] === 'string')) {
    return false;
  }
  if (!('name' in obj) || !(typeof obj['name'] === 'string')) {
    return false;
  }
  if (!('status' in obj) || !isPetStatus(obj['status'])) {
    return false;
  }
  if (!('createdAt' in obj) || !(typeof obj['createdAt'] === 'string')) {
    return false;
  }

  // Check optional properties if present
  if (
    'species' in obj &&
    !['dog', 'cat', 'bird', 'fish', 'other'].includes(obj['species'] as never)
  ) {
    return false;
  }
  if ('breed' in obj && !(typeof obj['breed'] === 'string')) {
    return false;
  }
  if ('age' in obj && !(typeof obj['age'] === 'number')) {
    return false;
  }
  if ('tags' in obj && !Array.isArray(obj['tags'])) {
    return false;
  }
  if ('owner' in obj && !isOwner(obj['owner'])) {
    return false;
  }
  if ('updatedAt' in obj && !(typeof obj['updatedAt'] === 'string')) {
    return false;
  }

  return true;
}

/**
 * Type guard for PetStatus enum
 *
 * @param value - The value to check
 */
export function isPetStatus(value: unknown): value is PetStatus {
  const validValues = ['available', 'pending', 'sold'] as const;
  return typeof value === 'string' && validValues.includes(value as (typeof validValues)[number]);
}

/**
 * Type guard for Owner
 *
 * @param value - The value to check
 */
export function isOwner(value: unknown): value is Owner {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const obj = value as Record<string, unknown>;

  // Check required properties
  if (!('id' in obj) || !(typeof obj['id'] === 'string')) {
    return false;
  }
  if (!('name' in obj) || !(typeof obj['name'] === 'string')) {
    return false;
  }
  if (!('email' in obj) || !(typeof obj['email'] === 'string')) {
    return false;
  }

  // Check optional properties if present
  if ('phone' in obj && !(typeof obj['phone'] === 'string')) {
    return false;
  }

  return true;
}

/**
 * Type guard for CreatePetRequest
 *
 * @param value - The value to check
 */
export function isCreatePetRequest(value: unknown): value is CreatePetRequest {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const obj = value as Record<string, unknown>;

  // Check required properties
  if (!('name' in obj) || !(typeof obj['name'] === 'string')) {
    return false;
  }

  // Check optional properties if present
  if (
    'species' in obj &&
    !['dog', 'cat', 'bird', 'fish', 'other'].includes(obj['species'] as never)
  ) {
    return false;
  }
  if ('breed' in obj && !(typeof obj['breed'] === 'string')) {
    return false;
  }
  if ('age' in obj && !(typeof obj['age'] === 'number')) {
    return false;
  }
  if ('tags' in obj && !Array.isArray(obj['tags'])) {
    return false;
  }

  return true;
}

/**
 * Type guard for UpdatePetRequest
 *
 * @param value - The value to check
 */
export function isUpdatePetRequest(value: unknown): value is UpdatePetRequest {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const obj = value as Record<string, unknown>;

  // Check optional properties if present
  if ('name' in obj && !(typeof obj['name'] === 'string')) {
    return false;
  }
  if (
    'species' in obj &&
    !['dog', 'cat', 'bird', 'fish', 'other'].includes(obj['species'] as never)
  ) {
    return false;
  }
  if ('breed' in obj && !(typeof obj['breed'] === 'string')) {
    return false;
  }
  if ('age' in obj && !(typeof obj['age'] === 'number')) {
    return false;
  }
  if ('status' in obj && !isPetStatus(obj['status'])) {
    return false;
  }
  if ('tags' in obj && !Array.isArray(obj['tags'])) {
    return false;
  }

  return true;
}

/**
 * Type guard for Photo
 *
 * @param value - The value to check
 */
export function isPhoto(value: unknown): value is Photo {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const obj = value as Record<string, unknown>;

  // Check required properties
  if (!('id' in obj) || !(typeof obj['id'] === 'string')) {
    return false;
  }
  if (!('url' in obj) || !(typeof obj['url'] === 'string')) {
    return false;
  }

  // Check optional properties if present
  if ('caption' in obj && !(typeof obj['caption'] === 'string')) {
    return false;
  }
  if ('uploadedAt' in obj && !(typeof obj['uploadedAt'] === 'string')) {
    return false;
  }

  return true;
}

/**
 * Type guard for Error
 *
 * @param value - The value to check
 */
export function isError(value: unknown): value is Error {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const obj = value as Record<string, unknown>;

  // Check required properties
  if (!('code' in obj) || !(typeof obj['code'] === 'string')) {
    return false;
  }
  if (!('message' in obj) || !(typeof obj['message'] === 'string')) {
    return false;
  }

  // Check optional properties if present
  if ('details' in obj && !(typeof obj['details'] === 'object' && obj['details'] !== null)) {
    return false;
  }

  return true;
}
